version: 0.0
os: linux
files:
  - source: dist
    destination: var/www/html/
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
